apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  config.yaml: |
    {{- $baseConfig := .Files.Get "config.yaml" | fromYaml }}
    {{- $overrideConfig := .Values.appConfigOverrides | default dict }}
    {{- $mergedConfig := mergeOverwrite (deepCopy $baseConfig) $overrideConfig }}
    {{- $mergedConfig | toYaml | nindent 8 }}
