apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount | default 2 }}
  selector:
    matchLabels:
      name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: DS_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: ds_api_key
        - name: PS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: ps_password
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: sentry_dsn
        - name: GIN_MODE
          value: "release"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT 
          value: "http://alloy:4318"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=contextdict"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/contextdict/config.yaml
          subPath: config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8086"
spec:
  selector:
    name: {{ .Release.Name }}
  ports:
    - protocol: TCP
      name: contextdict-port
      port: 8085
      targetPort: {{ .Values.appConfig.ServerPort}}
    - protocol: TCP
      name: contextdict-metric-port
      port: 8086
      targetPort: {{ .Values.appConfig.MetricsPort }}
