apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  ds_api_key: {{ .Values.secrets.dsApiKey | b64enc }}
  ps_password: {{ .Values.secrets.dbPassword | b64enc }}
  sentry_dsn: {{ .Values.secrets.sentryDsn | b64enc }}
