apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  ds_api_key: {{ .Values.secrets.ds_api_key | b64enc }}
  ps_password: {{ .Values.secrets.ps_password | b64enc }}
  sentry_dsn: {{ .Values.secrets.sentry_dsn | b64enc }}
