image:
  repository: zzhirong/contextdict
  tag: latest
  pullPolicy: IfNotPresent
appConfigOverrides:
secrets:
  dsApiKey: ""  # 将通过 --set-string secrets.dsApiKey=xxx 注入
  dbPassword: "" # 将通过 --set-string secrets.dbPassword=xxx 注入