name: Docker Build and Push on Tag

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker-build-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            zzhirong/contextdict:${{ github.ref_name }}
            zzhirong/contextdict:latest

      - name: Install Helm
        uses: azure/setup-helm@v4.3.0

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Configure K8s credentials
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy to K8s
        run: |
          helm upgrade --install contextdict ./charts/contextdict \
            --set-string image.tag='${{ github.ref_name }}' \
            --set-string secrets.dsApiKey='${{ secrets.DS_API_KEY }}' \
            --set-string secrets.dbPassword='${{ secrets.PS_PASSWORD }}' \
            --set-string secrets.sentryDsn='${{ secrets.SentryDsn }}'
