name: Docker Build and Push on Tag

on:
  push:
    tags:
      - '*'  # 监听所有 tag 的创建

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker-build-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            zzhirong/contextdict:${{ github.ref_name }}  # 使用 tag 名称作为镜像 tag
            zzhirong/contextdict:latest # Optionally, tag as latest
